Color Sensor publishes correct data.
frc5024/InfiniteRecharge pull request #108
Opened 2020-01-18 18:46 UTC by hyperliskdev

I think this can be improved with a less bright led in/near the sensor. There is no options to affect the brightness of the LED in the code.

2020-01-18 18:56 UTC, Keatonion approved these changes

2020-01-18 20:09 UTC, Ewpratten commented
@hyperliskdev There are merge conflicts. Can you fix this?

2020-01-19 22:54 UTC, ewpratten requested changes

2020-01-19 22:54 UTC, Ewpratten commented on src/main/java/frc/lib5k/components/ColorSensor5k.java
> +    public double getProx() {
I don't see any reason to have this

2020-01-19 22:54 UTC, Ewpratten commented on src/main/java/frc/lib5k/components/sensors/ColorSensor.java
> +/*
Please don't just copy-paste other libraries into ours. This is why @override exists.

2020-01-19 22:54 UTC, Ewpratten commented on src/main/java/frc/robot/RobotConstants.java
> +        public static Color8Bit redGameColor    = new Color8Bit(255, 0, 0);
Please use proper naming standards for constants (LIKE_THIS)

Also, this should be in fieldconstants, in its own sub-class

2020-01-19 22:54 UTC, Ewpratten commented on src/main/java/frc/lib5k/utils/Mathutils.java
> +    public static double logmap(double value, double min, double max) {
This needs a javadoc

2020-01-26 03:50 UTC, Ewpratten commented
Please add labels for your PR

2020-02-12 03:50 UTC, closed without merging