Stubbed harvester, hopper, and an intake command
frc5024/InfiniteRecharge pull request #120
Opened 2020-01-25 18:01 UTC by rsninja722

2020-01-25 19:49 UTC, Ewpratten commented
CI Failed with error:

```
 /github/workspace/src/main/java/frc/robot/subsystems/cellmech/Hopper.java:350: error: method getCellCount() is already defined in class Hopper
    public int getCellCount() {
```

2020-01-26 03:46 UTC, Ewpratten commented on src/main/java/frc/robot/autonomous/actions/subsystemActions/Intake.java
> +        m_target = Hopper.getInstance().getCellCount() + cellCount;
target should be equal to cellCount

2020-01-26 03:50 UTC, ewpratten requested changes

2020-01-26 03:50 UTC, Ewpratten commented on src/main/java/frc/robot/autonomous/actions/subsystemActions/Intake.java
> +        CellSuperstructure.getInstance().intakeStuff(m_count);
Please name this something useful

2020-01-26 03:50 UTC, Ewpratten commented on src/main/java/frc/robot/autonomous/actions/subsystemActions/Intake.java
> +        CellSuperstructure.getInstance().stopStuff();
This also needs a useful name

2020-01-26 03:50 UTC, Ewpratten commented on src/main/java/frc/robot/subsystems/cellmech/Hopper.java
> +            }
Holding a ball at any of these sensors will cause the ball count to rapidly increase or drop. These should be latched

2020-01-26 03:50 UTC, Ewpratten commented on src/main/java/frc/robot/subsystems/cellmech/Intake.java
> +        m_intakeRoller = new WPI_TalonSRX(RobotConstants.Intake.INTAKE_ROLLER_TALON);
This is apparently 2 talons following eachother, not one

2020-01-26 04:14 UTC, rsninja722 commented
Made the action purely a stub, reverted changes to superstructure, made roller use 2 motors. I fail to see how the cell count code will rapidly change, it only changes the cell count when the sensor changes states, and now only if the belt is supposed to be moving.

2020-01-26 04:15 UTC, rsninja722 commented
I will make superstructure have actual function on Tuesday

2020-01-26 16:51 UTC, Ewpratten commented
So you un-did your work? I cant check the diff right now

2020-01-26 16:51 UTC, Ewpratten commented
Requesting @awpratten for review

2020-01-26 17:47 UTC, rsninja722 commented
This was supposed to be just getting the hopper and intake into master, but then Will asked for a stub of an intake command for making autos. I don't know why I tried to make the stub have any function in the first place.

2020-01-26 20:18 UTC, Ewpratten commented
ah, ok

2020-02-02 19:27 UTC, ewpratten approved these changes

2020-02-02 19:28 UTC, Ewpratten commented
This PR is waiting on IRL testing, and #126 before merge

2020-02-10 02:48 UTC, Ewpratten commented
Replaced in favour of #146

2020-02-10 02:48 UTC, closed without merging